### PR TITLE
ENH: greatly speed up execution

### PR DESCRIPTION
**Pull request by andyfaff**
It's become clear from CI testing on scipy that the speed of the `cobyqa` method in `optimize.minimize` is definitely on the slow end, and needs to be improved. Please see https://github.com/scipy/scipy/issues/20724.

The inefficiency of the implementation is not because cobyqa takes too many iterations. Rather, there are inefficiencies in the way that the code is architected.

Unfortunately the performance is such that we may have to consider backing out the merge of the solver before we release the next scipy version. Given the amount of effort that's already been put into integrating the solver that's not a path that we would like to go down if at all possible.

In this PR I've attempted to tackle some of the low hanging fruit for trying to speed things up. This PR reduces the execution time by a factor of ~55% on test outlined in the linked issue.

Viz:
- repeated calls to `np.finfo` take a finite amount of time, so eliminate them.
- don't repeatedly calculate `problem.BoundConstraints.is_feasible`,  `problem.BoundConstraints.m` in a property. Create those attributes once on object creation.
- A lot of the infrastructure for calculating constraint slack, constraint violation, processing of constraints, etc, is already contained in `optimize._constraints.NonlinearConstraint`, `optimize._constraints.PreparedConstraint`, etc. Just use that prexisting infrastructure. It's easier for the scipy developers to maintain into the future. Furthermore this infrastructure already takes advantage of caching. Going forward new minimisers added to `scipy.optimize` will be directed to use `NonlinearConstraint`, `Bounds`, `LinearConstraint` instead of the old-school `dict` approach (which is more complicated to use), I therefore removed support for the dict based constraints. This also clears up the internals of the code.
- in `TrustRegion.merit`, only do linear algebra calculation when required.
- When building the A matrix of the interpolation system I've added caching to `build_system`.
- In `subsolvers.geometry.spider_geometry` lift some variables out of the loop by vectorising them.
- finally fix the cobyqa test suite to reflect the changes made. Also check against the `scipy.optimize` test suite.

The release period for scipy is just about to start (in the next 10 days or so). Given that there is very limited time is it possible to merge this PR within the next few days? The alternative is for us to back out the cobyqa merge into scipy, with a view to improving performance for the 1.15 release in about 6 months.

I appreciate any help you're able to give.

@zaikunzhang @ragonneau

### CODE REVIEW

**Comment by andyfaff** [comment]
Future efficiencies could include looking closely `cobyqa.Quadratic`. It's not clear to me why a lot of the methods, viz. `solve_systems`, `fun`, `grad`, `hess`, `hess_prod`, `curve`,  are given an interpolation each time. Why is the interpolation not just stored as an attribute? This might reduce repeated calls of `Quadratic.solve_systems` or permit caching. 
Only when the interpolation needs to be updated would an interpolation need to be supplied, e.g. `Quadratic.update`, `Quadratic.shift_x_base`.
Why is `Quadratic.solve_systems` a staticmethod?

Effectively I'm trying to reduce the number of calls to `scipy.linalg.eigh`.

**Comment by andyfaff** [comment]
The last commit, that caches the eigh call improves the performance yet again. On my local computer I get a 68% speed up (2.6 s --> 0.9 s) for the N=10 dimension rosenbrock function.

**Comment by zaikunzhang** [comment]
Thank you @andyfaff very much for proposing these improvements. We will discuss them. @ragonneau

**Comment by ragonneau** [comment]
Thank you very much @andyfaff. One question about `np.finfo(float).eps`, why should this improve the performance? Indeed, the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.finfo.html) of NumPy indicates that "The initial calculation of these parameters is expensive and negatively impacts import times. These objects are cached, so calling `finfo()` repeatedly inside your functions is not a problem."

Cheers,
Tom.

**Pull request merged**
